import {
  SITE_BRAND_EN,
  HERO_HEADLINE_NAME_LINES_EN,
  HERO_HEADLINE_ROLE_EN,
  HERO_SUBTITLE_EN,
  SITE_NAV_EN,
  PORTFOLIO_PROJECTS_EN,
  SKILL_ITEMS_EN,
  FOOTER_SOCIAL_LINKS_EN,
} from "./home_en";

import {
  SITE_BRAND_TH,
  HERO_HEADLINE_NAME_LINES_TH,
  HERO_HEADLINE_ROLE_TH,
  HERO_SUBTITLE_TH,
  SITE_NAV_TH,
  PORTFOLIO_PROJECTS_TH,
  SKILL_ITEMS_TH,
  FOOTER_SOCIAL_LINKS_TH,
} from "./home_th";

export {
  SITE_BRAND_EN,
  HERO_HEADLINE_NAME_LINES_EN,
  HERO_HEADLINE_ROLE_EN,
  HERO_SUBTITLE_EN,
  SITE_NAV_EN,
  PORTFOLIO_PROJECTS_EN,
  SKILL_ITEMS_EN,
  FOOTER_SOCIAL_LINKS_EN,
  SITE_BRAND_TH,
  HERO_HEADLINE_NAME_LINES_TH,
  HERO_HEADLINE_ROLE_TH,
  HERO_SUBTITLE_TH,
  SITE_NAV_TH,
  PORTFOLIO_PROJECTS_TH,
  SKILL_ITEMS_TH,
  FOOTER_SOCIAL_LINKS_TH,
};

// Common configurations
export const SITE_BRAND = "Kongkat Thanalertrungroj";
export const HERO_PORTRAIT_SRC = "/hero-portrait.jpg";
export const CONTACT_EMAIL = "kongkat5556@hotmail.com";
export const CONTACT_PHONE_DISPLAY = "+66 86-424-1979";
export const CONTACT_PHONE_TEL = "+66864241979";
export const NAV_SECTION_ORDER = ["about", "expertise", "work", "contact"] as const;

// Fallback arrays to avoid breaking references in non-localized components or build exports
export const PORTFOLIO_PROJECTS = PORTFOLIO_PROJECTS_EN;
export const SKILL_ITEMS = SKILL_ITEMS_EN;
export const SITE_NAV = SITE_NAV_EN;
export const FOOTER_SOCIAL_LINKS = FOOTER_SOCIAL_LINKS_EN;
export const HERO_HEADLINE_NAME_LINES = HERO_HEADLINE_NAME_LINES_EN;
export const HERO_HEADLINE_ROLE = HERO_HEADLINE_ROLE_EN;
export const HERO_SUBTITLE = HERO_SUBTITLE_EN;
